steps:
    - name: 'gcr.io/cloud-builders/go'
      args: ['install', 'soma']
      env: ['GOPATH=.'] 
      dir: 'CI'

    - id: "Go Test"
      name: "gcr.io/cloud-builders/go"
      args: ['test','-v','./...']
      env: ['GOPATH=.']
      dir: 'CI'

    - id: "Gerando Imagem"
      name: 'gcr.io/cloud-builders/docker'
      args: ['build','-t','gcr.io/$PROJECT_ID/desafio-ci:latest','-f','./dockerfile']
images: ['gcr.io/$PROJECT_ID/desafio-ci:latest']
    
