steps:
    - id: "Go Genarate"
      name: "gcr.io/cloud-builders/go"
      args: ["generate"]
      env: ['PROJECT_ROOT=github.com/gabriel301/codeeducation/tree/devops/cloudbuild/CI/src']
    
    - id: "Go Test"
      name: "gcr.io/cloud-builders/go"
      args: ["test","."]
      env: ['PROJECT_ROOT=github.com/gabriel301/codeeducation/tree/devops/cloudbuild/CI/src']

    - id: "Go Build/Install"
      name: 'gcr.io/cloud-builders/go'
      args: ['install', '-a', '-ldflags', "'-s'", '-installsuffix', 'cgo', 'github.com/gabriel301/codeeducation/tree/devops/cloudbuild/CI/src']
      env: [
            'PROJECT_ROOT=github.com/gabriel301/codeeducation/tree/devops/cloudbuild/CI/src',
            'CGO_ENABLED=0',
            'GOOS=linux'
          ]
images: ['gcr.io/$PROJECT_ID/desafio-ci:latest']
    
