steps:
    - id: "Go Test"
      name: "gcr.io/cloud-builders/go"
      args: ["test","."]
      env: ['GOPATH=$PWD']

    - name: 'gcr.io/cloud-builders/go'
      args: ['install', '.']
      env: ['GOPATH=$PWD']

    - id: "Gerando Imagem"
      name: 'gcr.io/cloud-builders/docker'
      args: ['build','-t','gcr.io/$PROJECT_ID/desafio-ci:latest','.']
images: ['gcr.io/$PROJECT_ID/desafio-ci:latest']
    
