FROM golang:alpine3.11 as build

WORKDIR /
#Copiando o fonte, compilado com a opção CGO_ENABLED=0 (CGO_ENABLED=0  go build -o ./build/main main.go)
COPY ./src/soma/soma.go .

RUN go install .
#Executa o executável
#ENTRYPOINT [ "./main" ]

FROM scratch
WORKDIR /
COPY --from=build / /
CMD ["/soma"]